"here you mention all student name which are doing node js"
"prabhakar chacha is from Uttar Pradesh"
"paranthaman is from Tamil Nadu"
"kirthiv is from Tamil Nadu"
"shabid khan is from Noida"
"tapas router is from noida"
"Biju nath is from Tamil Nadu"
"Aman pari is from Delhi"
"vishal Modi is from Bihar"
"kumar nayak is from Andhra pradesh"
"Ankur pandey is from Uttar pardesh"
"Ajay Udayan is from Noida"
"viresh is from karnataka"
"princeis from Noida"
"sanjay is from Delhi"
"yogesh is from Madhya Pradesh"
"Rohit is from Noida"